### ISSUE TITLE
Request for Details

### ISSUE THREAD

**Issue by mittaltripti** [appium/selenium-swift#1]
Hi,

We need to have more understanding on how this selenium-swift works. Following are few queries:-
1. Is selenium-swift a framework or just some jar to be used with selenium for iOS device automation ?
2. What is the actual purpose of selenium-swift ?
3. Will selenium-swift require appium also ? If yes, then how would appium and selenium both be combined ?
4. The read me is not very elaborative to understand the usage of selenium-swift. Please help with some detailed documentation of the same.

Requesting for some replies for the above queries at the earliest.

Thanks

**Comment by Jonahss** [comment]
Hello,

Appium is software program which runs as a server, and accepts commands over http. Those commands (which conform to the JSON Wire Protocol used by Selenium) can be sent from any programming language. We have created libraries for generating appium commands and receiving responses in most major languages. See the others here: http://appium.io/slate/en/master/?ruby#appium-client-libraries

The swift language binding doesn't have much community support right now, probably because almost nobody is writing tests in Swift. If you are interested in doing so, please learn as much as you can (try following appium examples in other languages) and feel free to submit pull requests to this repo.

**Comment by penguinho** [comment]
Note: I haven't finished this project yet either. So it's not entirely done
